name: credits_harness
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.1

dependencies:
  archive: ^4.3.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.2.0-beta.3
  flutter_local_notifications: ^22.3.1
  flutter_secure_storage: ^11.2.0
  html: ^0.15.7
  path: ^1.9.1
  shared_preferences: ^2.5.5
  timezone: ^0.11.1
  url_launcher: ^6.3.2
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/period_times.json
    - assets/js/
